---
title: "Water Quality Presentation2"
author: "Group 3: Stephanie Fissel, Beza Gashe, Claire Yoon"
date: "January 4, 2023"
output: 
  html_document:
    theme: lumen
    code_folding: hide
    toc: true
    toc_float:
      collapsed: false
      smooth_scroll: false
    toc_depth: 3
editor_options: 
chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(plyr)
library(plotly)
library(randomForest)
library(rio)
library(caret)
library(ROCR)
library(tidyverse)
library(rpart)
library(psych)
library(pROC)
library(rpart.plot)
library(rattle)
library(tidyverse)
library(class)
library(plotly)
library(MLmetrics)
library(mltools)
library(data.table)
library(RColorBrewer)
```


#### Read in the data
```{r}
#water_quality <- read.csv("/Users/stephaniefissel/Library/Mobile Documents/com~apple~CloudDocs/ds final project/water_potability.csv")
water_quality <- read.csv("~/Desktop/R/water-quality-project/water_potability.csv")

head(water_quality)
dim(water_quality)
```

### Clean the data
```{r}
water_quality <- water_quality[complete.cases(water_quality), ]
dim(water_quality)
```

### Rename and factorize the 'Potability' variable
```{r}
water_quality$Potability <- as.factor(water_quality$Potability)
water_quality$Potability <- fct_collapse(water_quality$Potability, 
                           potable = "1",
                           non_potable = "0")
```

### Splitting the data & Creating Decision trees
```{r}
#We do not need to check for correlated variables because correlation does not impact decision trees.
#Decision trees make greedy, localized decisions that are not dependent on previous steps or other variables in the tree model.  
set.seed(777)
partition <- caret::createDataPartition(water_quality$Potability,
                                           times=1,
                                           p = 0.80,
                                           groups=1,
                                           list=FALSE)
train <- water_quality[partition, ]
tune_and_test <- water_quality[-partition, ]
train

tune_and_test_index <- createDataPartition(tune_and_test$Potability,
                                           p = .5,
                                           list = FALSE,
                                           times = 1)

tune <- tune_and_test[tune_and_test_index, ]
test <- tune_and_test[-tune_and_test_index, ]

dim(train)
dim(test) 
dim(tune)

# Build the model
# Choose the features and classes, slightly different approach for caret, need to create features and target sets from the training data.
str(water_quality)
features <- train[,-10] # dropping the target variable
target <- train$Potability
str(features)

str(target)
fitControl <- trainControl(method = "repeatedcv",
                          number = 10,
                          repeats = 5,
                          classProbs = TRUE,
                          summaryFunction = twoClassSummary) 

tree.grid <- expand.grid(maxdepth=c(1:6))

# Train the model without setting tree grid
set.seed(777)
water_mdl1 <- train(x=features,
                y=target,
                method="rpart2",
                trControl=fitControl,
                metric="ROC")
plot(water_mdl1)
varImp(water_mdl1)
rpart.plot(water_mdl1$finalModel, type=1,extra=101)
water_mdl1 # maxdepth is 12

# Train the model
set.seed(777)
water_mdl2 <- train(x=features,
                y=target,
                method="rpart2",
                trControl=fitControl,
                tuneGrid=tree.grid,
                metric="ROC")

plot(water_mdl2)
varImp(water_mdl2)

rpart.plot(water_mdl2$finalModel, type=1,extra=101)

water_mdl2 # maxdepth is 6
```
```{r}
predictandCM<- function(model,data,modeltype,ref)
{
  pred <-predict(model,data,type=modeltype)
  confusionMatrix(pred, reference=ref, positive = 'non_potable')
}

predictandCM(water_mdl1, tune, "raw", tune$Potability)

predictandCM(water_mdl2, tune, "raw", tune$Potability) 

water_pred_tune = predict(water_mdl1,tune,tune$Potability, type= "prob")

water_pred_tune_labels = predict(water_mdl1,tune,tune$Potability,type = "raw")

View(as_tibble(water_pred_tune_labels))
```


```{r}
# Use the the confusion matrix function on your predictions to check a variety of metrics and comment on the metric that might be best for this type of analysis given your question.  

water_eval <- caret::confusionMatrix(water_pred_tune_labels, 
                as.factor(tune$Potability), 
                dnn=c("Prediction", "Actual"),
                positive="non_potable",
                mode = "everything")
water_eval
```
```{r}
# With the percentages you generated in step 10,select several different threshold levels using the threshold function we created and interpret the results. What patterns do you notice, did the evaluation metrics change?
plot(density(water_pred_tune$non_potable))

adjust_thres <- function(x, y, z) {
  #x=pred_probablities, y=threshold, z=tune_outcome
  thres <- as.factor(ifelse(x > y, "non_potable","potable"))
  confusionMatrix(thres, z, positive = "non_potable", dnn=c("Prediction", "Actual"), mode = "everything")
}

adjust_thres(water_pred_tune$non_potable,y=.4,tune$Potability)
```
